version: '2'

services:
    reverseproxy:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        restart: always

